// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://whjwhwhdrrpzrdmotvjw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indoandod2hkcnJwenJkbW90dmp3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxOTAyOTgsImV4cCI6MjA1Nzc2NjI5OH0.pF40i5MuQhMDlbId_jyyzn5s-jkQLupfm6ra9T31tqc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);